apiVersion: mcm-grcpolicy.ibm.com/v1alpha1
kind: IamPolicy
metadata:
  name: iam-grc-policy
  label: 
    category: "System-Integrity"
spec:
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  #labelSelector:
    #env: "production"
  remediationAction: enforce # enforce or inform
  maxRoleBindingUsersPerNamespace: 20
  