name: iam-policy-controller
version: 0.0.1
appVersion: 0.0.1
description: A Helm chart for deploying the Certificate Policy Controller
home: https://github.ibm.com/IBMPrivateCloud/iam-policy-controller
sources:
  - https://github.ibm.com/IBMPrivateCloud/iam-policy-controller
keywords:
  - expiration
  - grc
  - policy
  - mcm
  - tls
